#index:
#  path: /login
#  controller: App\Controller\DefaultController::index

ajout_etudiant:
  path:       /ajoutEtudiant
  controller: App\Controller\EtudiantController::new

ajout_enseignant:
  path:       /ajout
  controller: App\Controller\EnseignantController::new
